"""empty message

Revision ID: 077f966e8351
Revises: 
Create Date: 2021-07-21 14:15:31.529250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077f966e8351'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
