"""empty message

Revision ID: 1cecdd49773f
Revises: b447ec461ddf
Create Date: 2021-07-21 14:27:49.243508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cecdd49773f'
down_revision = 'b447ec461ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
