"""empty message

Revision ID: b447ec461ddf
Revises: 077f966e8351
Create Date: 2021-07-21 14:23:35.924058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b447ec461ddf'
down_revision = '077f966e8351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartIdentifier', 'CID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cartIdentifier', 'PID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
